const DATA=window.RML_DEFAULT_DATA;const FAMILLES=[...new Set(DATA.products.map(p=>p.famille))];const SECTION_NAMES=['ATELIER','GOUTTIERE','DESCENTE','COUVERTINE','HABILLAGE A FACON','MOYEN DE CHANTIER'];let state=JSON.parse(localStorage.getItem('rmlRentaState')||'null')||seed();let currentId=state.projects[0].id;let currentTab='estime';
function seed(){return{settings:DATA.settings,products:DATA.products,projects:[newProject()]}}
function newProject(){const mk=()=>SECTION_NAMES.map(n=>({name:n,lines:[]}));return{id:crypto.randomUUID(),created:new Date().toISOString(),client:'',chantier:'',equipiers:['','','',''],estime:mk(),reel:mk()}}
const euro=v=>(Number(v)||0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});const num=v=>Number(String(v??'').replace(',','.'))||0;function save(){localStorage.setItem('rmlRentaState',JSON.stringify(state));renderAll()}
function project(){return state.projects.find(p=>p.id===currentId)||state.projects[0]}
function calcLine(l){let q=num(l.qte),fo=num(l.fo),mo=num(l.mo),coef=num(l.coef)||num(state.settings.coefficients[l.famille])||1;let foT=q*fo,moT=q*mo,moE=moT*num(state.settings.couts.coutVendu),pr=foT+moE,pv=pr*coef;return{foT,moT,moE,pr,pv}}
function calcProject(p){let tot={fo:0,moE:0,pr:0,pvBase:0};['estime','reel'].forEach(type=>p[type].forEach(s=>s.lines.forEach(l=>{let c=calcLine(l);if(type==='estime'){tot.fo+=c.foT;tot.moE+=c.moE;tot.pr+=c.pr;tot.pvBase+=c.pv}})));tot.fg=tot.pvBase*state.settings.tauxFraisGeneraux;tot.pvFinal=tot.pvBase/(1-state.settings.tauxFraisGeneraux);tot.marge=tot.pvFinal-tot.pr;tot.tauxMarge=tot.pvFinal?tot.marge/tot.pvFinal:0;return tot}
function renderProjects(){let box=document.getElementById('projectList');box.innerHTML='';state.projects.forEach(p=>{let d=document.createElement('div');d.className='projectItem '+(p.id===currentId?'active':'');d.innerHTML=`<b>${p.chantier||'Chantier sans nom'}</b><br><small>${p.client||'Client non renseigné'}</small>`;d.onclick=()=>{currentId=p.id;renderAll()};box.appendChild(d)})}
function bindHeader(){let p=project();['client','chantier'].forEach(id=>{let el=document.getElementById(id);el.value=p[id]||'';el.oninput=()=>{p[id]=el.value;saveQuiet()}});[1,2,3,4].forEach((n,i)=>{let el=document.getElementById('eq'+n);el.value=p.equipiers[i]||'';el.oninput=()=>{p.equipiers[i]=el.value;saveQuiet()}})}function saveQuiet(){localStorage.setItem('rmlRentaState',JSON.stringify(state));renderProjects();renderKpis()}
function renderKpis(){let t=calcProject(project());document.getElementById('kpis').innerHTML=[['FO estimée',euro(t.fo)],['MO estimée',euro(t.moE)],['Prix revient',euro(t.pr)],['PV final avec FG',euro(t.pvFinal)],['Marge',euro(t.marge)+' / '+(t.tauxMarge*100).toFixed(1)+'%']].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderSections(type){let root=document.getElementById('sections-'+type);root.innerHTML='';project()[type].forEach(sec=>{let wrap=document.createElement('div');wrap.className='sectionBox';wrap.innerHTML=`<div class="sectionTitle"><h2>${sec.name}</h2><button class="addRow">Ajouter une ligne</button></div><div class="tableWrap"><table><thead><tr><th>Famille</th><th>Description</th><th>Fournisseur</th><th>Qté</th><th>Unité</th><th>FO unit.</th><th>FO total</th><th>MO unit.</th><th>MO total h</th><th>MO €</th><th>Coef</th><th>PR total</th><th>PV total</th><th></th></tr></thead><tbody></tbody></table></div><div class="totals"></div>`;let tbody=wrap.querySelector('tbody');sec.lines.forEach((l,i)=>tbody.appendChild(rowEl(l,sec,i,type)));wrap.querySelector('.addRow').onclick=()=>{sec.lines.push({famille:sec.name,designation:'',fournisseur:'',qte:0,unite:'u',fo:0,mo:0,coef:state.settings.coefficients[sec.name]||1});save()};root.appendChild(wrap);renderSectionTotals(wrap,sec)})}
function rowEl(l,sec,i,type){let tr=document.getElementById('rowTpl').content.firstElementChild.cloneNode(true);let fam=tr.querySelector('.famille');fam.innerHTML=FAMILLES.map(f=>`<option ${f===(l.famille||sec.name)?'selected':''}>${f}</option>`).join('');['designation','fournisseur','qte','unite','fo','mo','coef'].forEach(k=>{let el=tr.querySelector('.'+k);el.value=l[k]??'';el.oninput=()=>{l[k]=['qte','fo','mo','coef'].includes(k)?num(el.value):el.value;if(k==='designation')applyProduct(l);save()}});fam.onchange=()=>{l.famille=fam.value;l.coef=state.settings.coefficients[fam.value]||l.coef;save()};tr.querySelector('.delRow').onclick=()=>{sec.lines.splice(i,1);save()};let c=calcLine(l);tr.querySelector('.foTotal').textContent=euro(c.foT);tr.querySelector('.moTotal').textContent=c.moT.toFixed(2);tr.querySelector('.moEuro').textContent=euro(c.moE);tr.querySelector('.prTotal').textContent=euro(c.pr);tr.querySelector('.pvTotal').textContent=euro(c.pv);return tr}
function renderSectionTotals(wrap,sec){let s={fo:0,moE:0,pr:0,pv:0};sec.lines.forEach(l=>{let c=calcLine(l);s.fo+=c.foT;s.moE+=c.moE;s.pr+=c.pr;s.pv+=c.pv});wrap.querySelector('.totals').innerHTML=`<span>FO ${euro(s.fo)}</span><span>MO ${euro(s.moE)}</span><span>PR ${euro(s.pr)}</span><span>PV ${euro(s.pv)}</span>`}
function applyProduct(l){let p=state.products.find(p=>p.designation===l.designation);if(p){l.famille=p.famille;l.fournisseur=p.fournisseur||l.fournisseur;l.unite=p.unite||'u';l.fo=num(p.fo)||l.fo;l.mo=num(p.mo)||l.mo;l.coef=state.settings.coefficients[p.famille]||l.coef}}
function renderDatalist(){document.getElementById('productList').innerHTML=state.products.map(p=>`<option value="${p.designation.replaceAll('"','&quot;')}">${p.famille} - ${p.sousFamille}</option>`).join('')}
function renderCatalogue(){document.getElementById('coutVendu').value=state.settings.couts.coutVendu;document.getElementById('fg').value=state.settings.tauxFraisGeneraux*100;document.getElementById('coefDefault').value=1.5;let q=(document.getElementById('searchProduct').value||'').toLowerCase();let rows=state.products.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)).slice(0,250);document.getElementById('catalogueTable').innerHTML=`<div class="tableWrap"><table><thead><tr><th>Famille</th><th>Sous-famille</th><th>Désignation</th><th>FO</th><th>MO</th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td>${p.famille}</td><td>${p.sousFamille}</td><td>${p.designation}</td><td>${p.fo||''}</td><td>${p.mo||''}</td></tr>`).join('')}</tbody></table></div>`}
function renderAll(){renderProjects();bindHeader();renderKpis();renderDatalist();renderSections('estime');renderSections('reel');renderCatalogue()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabPane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active')});
document.getElementById('btnNew').onclick=()=>{let p=newProject();state.projects.unshift(p);currentId=p.id;save()};document.getElementById('btnSave').onclick=save;document.getElementById('btnDuplicate').onclick=()=>{let cp=JSON.parse(JSON.stringify(project()));cp.id=crypto.randomUUID();cp.chantier=(cp.chantier||'Chantier')+' - copie';state.projects.unshift(cp);currentId=cp.id;save()};document.getElementById('btnDelete').onclick=()=>{if(state.projects.length>1&&confirm('Supprimer ce chantier ?')){state.projects=state.projects.filter(p=>p.id!==currentId);currentId=state.projects[0].id;save()}};
document.getElementById('btnExport').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='rml-rentabilite-sauvegarde.json';a.click()};document.getElementById('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;f.text().then(t=>{state=JSON.parse(t);currentId=state.projects[0].id;save()})};document.getElementById('btnSettings').onclick=()=>{state.settings.couts.coutVendu=num(coutVendu.value);state.settings.tauxFraisGeneraux=num(fg.value)/100;SECTION_NAMES.forEach(n=>state.settings.coefficients[n]=num(coefDefault.value)||state.settings.coefficients[n]);save()};document.getElementById('searchProduct').oninput=renderCatalogue;document.getElementById('btnAddProduct').onclick=()=>{let d=prompt('Désignation du produit');if(d){state.products.unshift({famille:'GOUTTIERE',sousFamille:'',designation:d,fournisseur:'',unite:'u',fo:0,mo:0});save()}};renderAll();